folio-org/ui-serials-management

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml, package.json
Added appropriate GitHub Actions files buil-npm-release and build-npm, updated package.json
=> chore: Implement GA

package.json
Bumped react-query dependency to 3.9.0
=> chore: React-query bump

src/components/views/ExpectedPiecesView/ExpectedPiecesView.js, src/components/views/ExpectedPiecesView/index.js, src/components/views/PatternsView/PatternsView.js, src/components/views/PatternsView/index.js, src/components/views/index.js, src/index.js, src/routes/ExpectedPiecesRoute/ExpectedPiecesRoute.js, src/routes/ExpectedPiecesRoute/index.js, src/routes/PatternsRoute/PatternsRoute.js, src/routes/PatternsRoute/index.js, src/routes/SerialsRoute/SerialsRoute.js, src/routes/index.js, translations/ui-serials-management/en.json
Added initial setup of SASQRoute components for expected pieces and patterns
Also added initial translation for these and "found#Values"
=> feat: SASQRoutes

src/components/SearchAndFilter/RouteSwitcher/RouteSwitcher.js, src/components/SearchAndFilter/RouteSwitcher/index.js, src/components/SearchAndFilter/index.js, src/components/utils/index.js, src/components/utils/urls.js, src/routes/ExpectedPiecesRoute/ExpectedPiecesRoute.js, src/routes/PatternsRoute/PatternsRoute.js, src/routes/SerialsRoute/SerialsRoute.js
Added route switcher as header component to all SASQRoutes
=> feat: Route switcher component

package.json
Bumped stripes erm components to version 7.0.0
=> chore: Stripes-erm-components bump

src/components/SearchAndFilter/RouteSwitcher/RouteSwitcher.js, src/components/utils/index.js, src/components/utils/useSerialsManagementRefdata.js, src/constants/endpoints.js, src/index.js, src/settings/index.js
Added framework for settings page which will contain all serials management settings
=> feat: Settings page framework

translations/ui-serials-management/en.json, translations/ui-serials-management/en_US.json
Updated app display name from "Serials management" to "Serials"
=> chore: Updated display name

package.json
Added dependencies for react-final-form and react-final-form arrays
=> dep: React-final-form dependencies

src/components/utils/urls.js, src/components/views/SerialForm/SerialForm.js, src/components/views/SerialForm/index.js, src/components/views/index.js, src/index.js, src/routes/SerialCreateRoute/SerialCreateRoute.js, src/routes/SerialCreateRoute/index.js, src/routes/SerialsRoute/SerialsRoute.js, src/routes/index.js, translations/ui-serials-management/en.json
Added framework for create/edit serial record form
=> feat: Create serial framework

src/components/SerialFormSections/POLineLookup/POLineLookup.js, translations/ui-serials-management/en.json
Changed "poLineSpecific" value to be more general to allow for usage of values other than titleOrPackage
=> chore: Updated translations

src/components/SerialFormSections/POLineForm/POLineForm.js, src/components/SerialFormSections/POLineLookup/POLineLookup.js, src/components/utils/urls.js, src/constants/endpoints.js, src/hooks/index.js, src/hooks/useMaterialType.js, src/hooks/useOrder.js, src/hooks/useOrders.js, src/hooks/useVendor.js, translations/ui-serials-management/en.json
Added Vendor, funds, material type and order number/status fields to the PO Line lookup form card along with associated endpoints and hooks to allow for fetching of relevant information
=> feat: PO Line card info

src/components/SerialFormSections/POLineForm/POLineForm.js, src/components/SerialFormSections/POLineLookup/POLineLookup.js, src/constants/endpoints.js, src/hooks/index.js, src/hooks/useIdentifierTypes.js, src/hooks/useVendor.js, translations/ui-serials-management/en.json
Added functionality to fetch and render PO Line product identifier types within PO Lilne lookup card
=> feat: PO Line identifier types

src/components/SerialFormSections/POLineForm/POLineForm.js, src/constants/endpoints.js, src/routes/SerialCreateRoute/SerialCreateRoute.js, src/routes/SerialsRoute/SerialsRoute.js
Added route and endpoint for creating new serial records along with basic display for serials within the SASQRoute
=> feat: Create serial route

src/routes/SerialsRoute/SerialsRoute.js
Added formatter to serials SASQ lookup component to ensure that linked PO Line information is show within the MCL
=> feat: Serials lookup formatter

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml
Removed bigtest actions from build-npm yaml files
=> chore: Bigtest removal

src/components/SearchAndFilter/RouteSwitcher/RouteSwitcher.js, src/routes/ExpectedPiecesRoute/ExpectedPiecesRoute.js, src/routes/PatternsRoute/PatternsRoute.js, src/routes/SerialsRoute/SerialsRoute.js
Implemented ResponiveButtonGroup into SASQLookup filter pane to allow for correct resizing
[UISER-9](https://issues.folio.org/browse/UISER-9)
=> feat: ResponsiveButtonGroup

src/routes/SerialsRoute/SerialsRoute.js
Added a temporary serial ID field to serials SASQ lookup component until PO line number, product ids and titles are stored locally
=> fix: Temporary serial ID

package.json
Bumped stripes dependency to V8
[UISER-10](https://issues.folio.org/browse/UISER-10)
=> UISER-10: Stripes 8.0.0

src/components/SearchAndFilter/POLineFilter/POLineFilter.js, src/components/SearchAndFilter/POLineFilter/index.js, src/components/SearchAndFilter/SerialsFilters/SerialsFilters.js, src/components/SearchAndFilter/SerialsFilters/index.js, src/components/SearchAndFilter/index.js, src/routes/ExpectedPiecesRoute/ExpectedPiecesRoute.js, src/routes/PatternsRoute/PatternsRoute.js, src/routes/SerialsRoute/SerialsRoute.js
Added filter button to allow for filtering of serials by linked PO Line
[UISER-3](https://issues.folio.org/browse/UISER-3)
=> feat: Po line filter

src/components/SerialFormSections/POLineForm/POLineForm.js, src/components/SerialFormSections/SerialInfoForm/SerialInfoForm.js, src/components/SerialFormSections/SerialInfoForm/index.js, src/components/SerialFormSections/index.js, src/components/utils/index.js, src/components/utils/selectifyRefdata.js, src/components/views/SerialForm/SerialForm.js, src/hooks/useIdentifierTypes.js, src/routes/SerialCreateRoute/SerialCreateRoute.js, src/routes/SerialEditRoute/SerialEditRoute.js, translations/ui-serials-management/en.json
Fixed query to identifier-types so that correct ids are returned based on productIdType
=> fix: Identifier type query

src/components/SerialFormSections/SerialNoteFieldArray/SerialNoteFieldArray.js, src/components/SerialFormSections/SerialNoteFieldArray/index.js, src/components/SerialFormSections/index.js, src/components/views/SerialForm/SerialForm.js, translations/ui-serials-management/en.json
Added field array for serial notes, may need some refactoring for consistency in the future
[UISER-1](https://issues.folio.org/browse/UISER-1)
=> feat: Serial notes

src/components/SerialFormSections/POLineForm/POLineForm.js
Fixed PO Line car "View in inventory" link to ensure that a link is conditionally rendered if an instanceId is present
=> fix: Inventory link

src/components/SerialFormSections/POLineForm/POLineForm.js
Inventory link conditional is now correctly styled if instanceId is present or not
=> style: Inventory link

src/components/SerialFormSections/POLineForm/POLineForm.js, src/constants/endpoints.js, src/hooks/index.js, src/hooks/useAcqUnits.js, translations/ui-serials-management/en.json
Added acq units to PO Line lookup card display
=> feat: Acquisition units

src/components/SerialFormSections/POLineForm/POLineForm.js, src/hooks/useVendor.js
Tweaked PO line card to correctly display Loading when related items are still in the process of being fetched
=> refactor: PO line card tweaks

src/components/SerialFormSections/POLineForm/POLineForm.js, src/components/SerialSections/SerialInfo/SerialInfo.js, src/components/SerialSections/SerialInfo/index.js, src/components/SerialSections/SerialPOLine/SerialPOLine.js, src/components/SerialSections/SerialPOLine/index.js, src/components/SerialSections/index.js, src/components/views/SerialView/SerialView.js
Added metadata, status and description keyvalues to serial view
Added PO Line to serials view
=> feat: Serial view

src/components/views/SerialForm/SerialForm.js
Fixed issue in which serial form pane was always displaying "edit serial", added id to conditional so only serials that already have assigned id will display this header
=> fix: Edit serial header

src/components/RecurrenceFormSections/IssuePublicationField/IssuePublicationField.js, src/components/RecurrenceFormSections/PatternTimePeriodForm/PatternTimePeriodForm.js, src/routes/SerialCreateRoute/SerialCreateRoute.js, src/routes/SerialEditRoute/SerialEditRoute.js
Values are now correctly displayed within the edit form
=> fix: Edit form value display

src/components/RecurrenceFormSections/IssuePublicationField/IssuePublicationField.js, src/components/RecurrenceFormSections/PatternTimePeriodForm/PatternTimePeriodForm.js, src/constants/sortedArrays.js
Added sorted values to time unit, weekday and month fields
=> feat: Sorted select fields

src/components/RecurrenceFormSections/IssuePublicationField/IssuePublicationField.js, src/components/RecurrenceFormSections/IssuePublicationFieldArray/IssuePublicationFieldArray.js, src/components/RecurrenceFormSections/PatternTimePeriodForm/PatternTimePeriodForm.js, src/hooks/usePatternTypes.js, src/routes/SerialCreateRoute/SerialCreateRoute.js
Added initial fix for day/week time unit recurrence
=> fix: Day/Week time unit

src/components/RecurrenceFormSections/IssuePublicationField/IssuePublicationField.js
Fixed issue in which min/max values were inverted due to ordinal arg changes within day/week fields
=> fix: IssuePublicationField min/max value

src/components/RecurrenceFormSections/IssuePublicationField/IssuePublicationField.js
Fixed an issue in which deleting the final item from the field array would result in the issues field not validating on 0
=> fix: Issues validation

src/components/SerialSections/Rulesets/Rulesets.js, translations/ui-serials-management/en.json
Changed translations for rulesets accordion within serial view pane
=> chore: Rulesets translation

src/components/RulesetFormSections/IssuePublicationField/IssuePublicationField.js
Updated weekday/month refdata category from RecurrencePattern to global due to backend changes
=> refactor: Weekday/Month refdata category

src/components/RulesetFormSections/IssuePublicationFieldArray/IssuePublicationFieldArray.js, src/components/RulesetFormSections/OmissionField/OmissionField.js, src/components/RulesetFormSections/OmissionFieldArray/OmissionFieldArray.js, src/components/RulesetFormSections/PatternTimePeriodForm/PatternTimePeriodForm.js, src/constants/sortedArrays.js, src/hooks/index.js, src/hooks/useOmissionPatternTypes.js, src/hooks/useRecurrencePatternTypes.js
Reworked omissions to include a 'Time unit' field for more options with regards to omission pattern type, backend work still needed
=> feat: Omission rework

src/components/PiecesPreviewModal/PiecesPreviewModal.js, src/components/PiecesPreviewModal/index.js, src/components/views/RulesetForm/RulesetForm.js, src/components/views/SerialView/SerialView.js, src/constants/endpoints.js, translations/ui-serials-management/en.json
Added preview button and modal to ruleset for generating predicted pieces and returning a list of LocalDates
=> feat: Piece generation preview

src/components/PiecesPreviewModal/PiecesPreviewModal.js, translations/ui-serials-management/en.json
Added multicolumn list to predicted pieces modal for correct formatting of results for ease of testing
=> feat: Predicted pieces formatting

src/hooks/useOmissionPatternTypes.js
Updated omission type translations to reflect previous changes
=> refactor: Updated omission types

src/components/RulesetFormSections/PatternTimePeriodForm/PatternTimePeriodForm.js
Adjusted the maximum number of years from 20 to 10 per recurrence
=> refactor: Year max period

package.json, src/routes/RulesetCreateRoute/RulesetCreateRoute.js
Added service-interactions to dependencies and implemented the useGenerateNumber hook for generation of rulesetNumber within RulesetCreateRoute
[UISER-34](https://issues.folio.org/browse/UISER-34)
=> feat: Ruleset number generation

src/components/RulesetFormSections/PatternTimePeriodForm/PatternTimePeriodForm.js
Fixed conditional for creating issues field array based on time unit limiters
=> fix: Issues field array generator

src/components/SerialSections/ActivePublicationPattern/ActivePublicationPattern.js, src/components/SerialSections/DeprecatedPublicationPatterns/DeprecatedPublicationPatterns.js, src/components/SerialSections/DeprecatedPublicationPatterns/index.js, src/components/SerialSections/index.js, src/components/views/SerialView/SerialView.js, translations/ui-serials-management/en.json
Added deprecated publication patterns to the serial view pane
[UISER-33](https://issues.folio.org/browse/UISER-33)
=> feat: Deprecated publication patterns

src/hooks/useRecurrencePatternTypes.js
Adjusted year_month_weekday translation for day field to correctly match field values
[UISER-36](https://issues.folio.org/browse/UISER-36)
=> fix: Recurrence pattern type label

src/components/RulesetFormSections/ChronologyField/ChronologyField.js, src/components/RulesetFormSections/EnumerationField/EnumerationField.js, src/constants/selectOptionTranslations.js
Added translation placeholders for chronology and enumeration format fields
=> feat: Labelling translations

src/components/PiecesPreviewModal/PiecesPreviewModal.js, src/components/RulesetFormSections/ChronologyField/ChronologyField.js, src/components/RulesetFormSections/EnumerationCyclicalField/EnumerationCyclicalField.js, src/components/RulesetFormSections/EnumerationCyclicalField/index.js, src/components/RulesetFormSections/EnumerationCyclicalFieldArray/EnumerationCyclicalFieldArray.js, src/components/RulesetFormSections/EnumerationCyclicalFieldArray/index.js, src/components/RulesetFormSections/EnumerationField/index.js, src/components/RulesetFormSections/EnumerationFieldArray/index.js, src/components/RulesetFormSections/EnumerationNumericField/EnumerationNumericField.js, src/components/RulesetFormSections/EnumerationNumericField/index.js, src/components/RulesetFormSections/EnumerationNumericFieldArray/EnumerationNumericFieldArray.js, src/components/RulesetFormSections/EnumerationNumericFieldArray/index.js, src/components/RulesetFormSections/LabelFieldArray/LabelFieldArray.js, src/components/RulesetFormSections/index.js, translations/ui-serials-management/en.json
Refactored frontend to account for changes made to backend modelling
=> refactor: Templating changes

src/components/RulesetFormSections/EnumerationCyclicalField/index.js, src/components/RulesetFormSections/EnumerationCyclicalFieldArray/index.js, src/components/RulesetFormSections/EnumerationTextualField/EnumerationTextualField.js, src/components/RulesetFormSections/EnumerationTextualField/index.js, src/components/RulesetFormSections/EnumerationTextualFieldArray/EnumerationTextualFieldArray.js, src/components/RulesetFormSections/EnumerationTextualFieldArray/index.js, src/components/RulesetFormSections/LabelFieldArray/LabelFieldArray.js, src/components/RulesetFormSections/index.js
Renamed EnumerationCyclical to ENumerationTextual as per changes made to back end
=> refactor: Cyclical to Textual

src/components/SerialFormSections/POLineForm/POLineForm.js
Removed required prop and validator from POLine lookup
=> fix: Removed POLine required

src/components/PiecesPreviewModal/PiecesPreviewModal.js, src/components/utils/urls.js, src/components/views/RulesetForm/RulesetForm.js, src/components/views/SerialView/SerialView.js
Added framework modal for create of predicted piece sets
=> feat: Create pieces modal

src/components/PieceSetSections/PiecesList/PiecesList.js, src/components/PiecesPreviewModal/PiecesPreviewModal.js, translations/ui-serials-management/en.json
Reformatted display of omitted pieces within pieces list and preview modal
=> feat: Omitted badge

src/components/SearchAndFilter/SerialsFilters/SerialsFilters.js, src/routes/SerialsRoute/SerialsRoute.js
Implemented status filter to serials SASQ
=> feat: Serial status filter

src/components/PieceSetSections/PieceSetInfo/PieceSetInfo.js, src/routes/PieceSetsRoute/PieceSetsRoute.js
Implemented view of pattern ID to both the piece set sasq and view pane
=> feat: PatternId view

src/components/GenerateReceivingModal/GenerateReceivingModal.js, src/components/views/PieceSetView/PieceSetView.js, src/hooks/useHoldings.js, src/hooks/useLocations.js, translations/ui-serials-management/en.json
Refactored some of the identification of locations/holding within the receiving modal
=> refactor: Generate receiving refactor

src/routes/SerialsRoute/SerialsRoute.js
Displayed title in serial SASQ lookup
=> feat: Dislpay serial title

src/components/PiecesPreviewModal/PiecesPreviewModal.css, src/components/PiecesPreviewModal/PiecesPreviewModal.js, translations/ui-serials-management/en.json
Added fields to pieces preview modal for enumeration numeric starting values
Adjusted starting values format
Updated formatting, validation to fields and passing of index and initial values
=> Enumeration numeric starting  values

src/components/PiecesPreviewModal/PiecesPreviewModal.js
Ensured that the entire ruleset is now passed to backend for consistent management within the controller
=> refactor: Handle creation tweak

src/components/GenerateReceivingModal/GenerateReceivingModal.js
The interval of a receiving piece is now correctly added to the piece date that is provided
=> fix: Receiving piece interval

src/components/PieceSetSections/PieceSetInfo/PieceSetInfo.js, src/components/SerialSections/ActivePublicationPattern/ActivePublicationPattern.js, src/components/SerialSections/DeprecatedPublicationPatterns/DeprecatedPublicationPatterns.js, src/components/SerialSections/SerialPieceSets/SerialPieceSets.js, src/routes/PieceSetsRoute/PieceSetsRoute.js
Fixed prop for formatted date time from value to date
[UISER-89](https://folio-org.atlassian.net/browse/UISER-89)
=> fix: Formatted date time value prop

src/routes/RulesetCreateRoute/RulesetCreateRoute.js, src/routes/SerialsRoute/SerialsRoute.js
Added title and description search to serials search & sort screen
[UISER-81](https://folio-org.atlassian.net/jira/software/c/projects/UISER/issues/UISER-81)
=> feat: Title and description search

src/components/PiecesPreviewModal/PiecesPreviewModal.js, src/components/RulesetFormSections/EnumerationTextualField/EnumerationTextualField.js, src/components/RulesetFormSections/EnumerationTextualFieldArray/EnumerationTextualFieldArray.js, translations/ui-serials-management/en.json
Updated enumeration textual label text fields to use refdata as opposed to pure text
=> feat: Enumeration textual refdata

src/settings/index.js, src/settings/routes/PickListSettings.js, src/settings/routes/index.js, translations/ui-serials-management/en.json
Added pick lists pane to setting for addition of refdata categories
=> feat: Pick lists settings pane

package.json
Added optional dependency for plugin-find-po-line
=> build: plugin-find-po-line optional dep

package.json
Added optional dependency for plugin-find-po-line
=> build: plugin-find-po-line optional dep (#166)

README.md
[UISER-98](https://folio-org.atlassian.net/browse/UISER-96)
=> UISER-98: Added information on optional dependencies in the README

package.json
Bumped @folio/service-interaction dependency to 2.0.0 from 1.0.0
=> build: Bumped service-interaction dependency

src/components/views/PieceSetView/PieceSetView.js
Fixed an error in which holding IDs were not correctly being passed to receiving modal
[UISER-94](https://folio-org.atlassian.net/browse/UISER-94)
=> fix: Holding options fix

src/components/GenerateReceivingModal/GenerateReceivingModal.js, src/components/PieceSetSections/PiecesList/PiecesList.js, src/components/PiecesPreviewModal/PiecesPreviewModal.js, src/components/RulesetFormSections/ChronologyField/ChronologyField.js, src/components/RulesetFormSections/CombinationField/CombinationField.js, src/components/RulesetFormSections/CombinationFieldArray/CombinationFieldArray.js, src/components/RulesetFormSections/EnumerationNumericField/EnumerationNumericField.js, src/components/RulesetFormSections/EnumerationTextualField/EnumerationTextualField.js, src/components/RulesetFormSections/IssuePublicationField/IssuePublicationField.js, src/components/RulesetFormSections/LabelFieldArray/LabelFieldArray.js, src/components/RulesetFormSections/OmissionField/OmissionField.js, src/components/RulesetFormSections/OmissionFieldArray/OmissionFieldArray.js, src/components/RulesetFormSections/PatternTimePeriodForm/PatternTimePeriodForm.js, src/components/SearchAndFilter/SerialsFilters/SerialsFilters.js, src/components/SerialFormSections/POLineForm/POLineForm.js, src/components/SerialSections/ActivePublicationPattern/ActivePublicationPattern.js, src/components/SerialSections/DeprecatedPublicationPatterns/DeprecatedPublicationPatterns.js, src/components/SerialSections/SerialPOLine/SerialPOLine.js, src/components/SerialSections/SerialPieceSets/SerialPieceSets.js, src/components/utils/selectifyRefdata.js, src/routes/PieceSetsRoute/PieceSetsRoute.js, src/routes/RulesetCreateRoute/RulesetCreateRoute.js, src/routes/SerialCreateRoute/SerialCreateRoute.js, src/routes/SerialEditRoute/SerialEditRoute.js, translations/ui-serials-management/en.json
Fixed majority of code smells, bugs and duplication issues flagged by the Sonarqube reports
[UISER-107](https://folio-org.atlassian.net/browse/UISER-107)
=> chore: Sonarqube fixes

src/components/SerialSections/ActivePublicationPattern/ActivePublicationPattern.js, src/components/SerialSections/ActivePublicationPattern/ActivePublicationPattern.test.js
Changed props within Publication pattern accordion to be open by default
[UISER-101](https://folio-org.atlassian.net/jira/software/c/projects/UISER/issues/UISER-101)
=> feat: Publication pattern open by default

src/components/SerialFormSections/POLineForm/POLineForm.js, src/components/SerialPOLineInfo/SerialPOLineInfo.js, src/components/SerialPOLineInfo/index.js, src/components/SerialSections/SerialPOLine/SerialPOLine.js
Seperated out duplicate code from SerialPOLine and POLineForm into a seperate component
=> refactor: Serial PO line info

src/components/PiecePublicationDate/PiecePublicationDate.js, src/components/PiecePublicationDate/index.js, src/components/PieceSetSections/PiecesList/PiecesList.js, src/components/PiecesPreviewModal/PiecesPreviewModal.js
Seperated out piece publication date into a component to reduce duplication
=> refactor: Piece publication date

src/components/GenerateReceivingModal/GenerateReceivingModal.js
Added aria labels to holding and supplement fields within generate receiving modal
[UISER-76](https://folio-org.atlassian.net/browse/UISER-76)
=> fix: Receiving modal aria labels

src/components/RulesetFormSections/EnumerationNumericField/EnumerationNumericField.js
Fixed translation for number of units aria label within enumeration numeric
[UISER-68](https://folio-org.atlassian.net/browse/UISER-68)
=> fix: Number of units aria label

src/components/RulesetFormSections/EnumerationTextualField/EnumerationTextualField.js
Added required and whole number valdation to units field and added aria labels to fields
[UISER-69](https://folio-org.atlassian.net/browse/UISER-69)
=> fix: Enumeration textual field tweaks

src/components/PieceSetSections/PieceSetInfo/PieceSetInfo.js, src/components/PieceSetSections/PieceSetInfo/PieceSetInfo.test.js, src/components/PieceSetSections/PiecesList/PiecesList.test.js, src/components/PiecesPreviewModal/PiecesPreviewModal.test.js, src/components/RulesetFormSections/ChronologyField/ChronologyField.test.js, src/components/RulesetFormSections/CombinationField/CombinationField.js, src/components/RulesetFormSections/CombinationField/CombinationField.test.js, src/components/RulesetFormSections/CombinationFieldArray/CombinationFieldArray.test.js, src/components/RulesetFormSections/EnumerationNumericField/EnumerationNumericField.js, src/components/RulesetFormSections/EnumerationNumericField/EnumerationNumericField.test.js, src/components/RulesetFormSections/EnumerationNumericFieldArray/EnumerationNumericFieldArray.test.js, src/components/RulesetFormSections/EnumerationTextualField/EnumerationTextualField.js, src/components/RulesetFormSections/EnumerationTextualField/EnumerationTextualField.test.js, src/components/RulesetFormSections/OmissionField/OmissionField.js, src/components/RulesetFormSections/OmissionField/OmissionField.test.js, src/components/RulesetFormSections/OmissionFieldArray/OmissionFieldArray.js, src/components/RulesetFormSections/OmissionFieldArray/OmissionFieldArray.test.js, src/components/RulesetFormSections/RulesetInfoForm/RulesetInfoForm.test.js, src/components/SerialFormSections/SerialInfoForm/SerialInfoForm.js, src/components/SerialFormSections/SerialInfoForm/SerialInfoForm.test.js, src/components/SerialFormSections/SerialNoteFieldArray/SerialNoteFieldArray.test.js, src/components/SerialSections/DeprecatedPublicationPatterns/DeprecatedPublicationPatterns.test.js, src/components/SerialSections/SerialPOLine/SerialPOLine.test.js, src/components/SerialSections/SerialPieceSets/SerialPieceSets.test.js, test/resources/index.js, test/resources/ruleset.js
Rebased from Monirehs fork will so confilict resolutions
[UISER-51](https://folio-org.atlassian.net/browse/UISER-51)
=> test: Code coverage

src/routes/SerialsRoute/SerialsRoute.js
Fixed accessibility issue “Certain ARIA roles must contain particular children” within serials search and sort
[UISER-64](https://folio-org.atlassian.net/browse/UISER-64)
=> fix: Accessibility serials search and sort

package.json
Previous commit bumped service-interaction peer dep but not the dev dep
=> build: Service interaction

src/components/RulesetFormSections/EnumerationTextualFieldArray/EnumerationTextualFieldArray.js, src/components/RulesetFormSections/EnumerationTextualFieldArray/EnumerationTextualFieldArray.test.js
Added more in depth testing for EnumerationTextualFieldArray component
=> test: Test coverage for EnumerationTextualFieldArray

src/components/RulesetFormSections/CombinationFieldArray/CombinationFieldArray.js, src/components/RulesetFormSections/CombinationFieldArray/CombinationFieldArray.test.js, test/resources/refdata.js
Bumped test coverage on CombinationFieldArray
=> test: Update coverage on CombinationFieldArray

src/index.test.js
Initial commit on serials-management
=> test: index.js

src/components/SerialSections/ActivePublicationPattern/index.js, src/components/SerialSections/PublicationPattern/PublicationPattern.js, src/components/SerialSections/PublicationPattern/PublicationPattern.test.js, src/components/SerialSections/PublicationPattern/index.js, src/components/SerialSections/index.js, src/components/views/SerialView/SerialView.js, src/components/views/SerialView/SerialView.test.js
Renamed ActivePublicationPattern to PublicationPattern
=> refactor: Renamed ActivePublicationPattern

src/routes/RulesetCreateRoute/RulesetCreateRoute.js
Refactored ruleset submit handler
=> refactor: Ruleset create submit

src/components/GenerateReceivingModal/GenerateReceivingModal.js, src/components/PieceSetSections/PiecesList/PiecesList.js, src/components/PiecesPreviewModal/PiecesPreviewModal.js, src/components/RulesetFormSections/EnumerationNumericFieldArray/EnumerationNumericFieldArray.js, src/components/RulesetFormSections/IssuePublicationFieldArray/IssuePublicationFieldArray.js, src/components/SerialSections/DeprecatedPublicationPatterns/DeprecatedPublicationPatterns.js, src/components/SerialSections/SerialPieceSets/SerialPieceSets.js, src/routes/PieceSetsRoute/PieceSetsRoute.js, src/routes/SerialsRoute/SerialsRoute.js
Fixed all critical and major code smells flagged by sonar cloud
UISER-119
=> fix: Sonar cloud code smells

src/components/PiecesPreviewModal/PiecesPreviewModal.js, src/components/RulesetFormSections/OmissionField/OmissionField.js, src/components/RulesetFormSections/PatternTimePeriodForm/PatternTimePeriodForm.js
Refactored the handle generation code for prieving predicted pieces
=> refactor: Piece preview generation

package.json, src/components/SerialFormSections/POLineForm/POLineForm.js, src/routes/SerialCreateRoute/SerialCreateRoute.js, src/routes/SerialEditRoute/SerialEditRoute.js
Fixed an issue in which titleIds were not being saved correctly
=> fix: TitleId saving

src/components/SerialSections/PublicationPattern/PublicationPattern.css, src/components/SerialSections/PublicationPattern/PublicationPattern.js, translations/ui-serials-management/en.json
Is empty message will now be displayed when no active publicaiton pattern is assigned to a serial
=> fix: Added is empty message to publication pattern accordion

src/components/PiecesPreviewModal/PiecesPreviewModal.js
Added additional required validators for the enumeration numeric starting value fields, additionally made tweaks to the submit handling due to refactors made within mod-serials-management
[UISER-115](https://folio-org.atlassian.net/browse/UISER-115), [UISER-99](https://folio-org.atlassian.net/browse/UISER-99)
=> UISER-115/99: Starting values for each enumeration level should be required

src/components/PiecePublicationDate/PiecePublicationDate.test.js, src/components/RulesetFormSections/LabelFieldArray/LabelFieldArray.js, src/components/RulesetFormSections/LabelFieldArray/LabelFieldArray.test.js, src/constants/endpoints.js, src/hooks/index.js, src/hooks/useLocales.js, test/resources/index.js, test/resources/locales.js
Added locale field for chronology through which a locale for a chronology label can be added
UISER-113
=> UISER-113: Support using different languages for chronologies when generating predicted pieces

src/components/RulesetFormSections/ChronologyField/ChronologyField.test.js, translations/ui-serials-management/en.json, translations/ui-serials-management/en_US.json
Updated chronology month number to correctly reflect cotober
=> fix: Chronology month number tweak

src/components/PieceSetSections/PieceSetInfo/PieceSetInfo.js, src/components/PieceSetSections/PieceSetInfo/PieceSetInfo.test.js, src/components/SerialSections/SerialInfo/SerialInfo.js, src/components/SerialSections/SerialInfo/SerialInfo.test.js, src/components/utils/urls.js, src/components/views/PieceSetView/PieceSetView.js, test/resources/pieceSet.js, translations/ui-serials-management/en.json
- add row to PieceSetInfo and SerialInfo
- add titleId to pieceSet object in PieceSetView
- add translation
- extend tests
=> UISER-112 Add linked title to Serial display and Predicted piece set display

src/components/GenerateReceivingModal/GenerateReceivingModal.js, translations/ui-serials-management/en.json
Improved feedback for users upon generating receiving pieces by adding success and error callouts
=> fix: Improve information and feedback to user when generating receiving pieces

src/components/GenerateReceivingModal/GenerateReceivingModal.js
Added spinner to receving modal whilst submitting
=> fix: Receiving spinner

src/components/GenerateReceivingModal/GenerateReceivingModal.js, src/routes/PieceSetsRoute/PieceSetsRoute.js, translations/ui-serials-management/en.json
Added an error callout to be thrown when pieces cannot be generated in receiving
=> fix: Generate receiving error handling

src/components/RulesetFormSections/IssuePublicationField/IssuePublicationField.js, src/components/RulesetFormSections/IssuePublicationField/IssuePublicationField.test.js, src/components/RulesetFormSections/IssuePublicationFieldArray/IssuePublicationFieldArray.js, src/components/RulesetFormSections/LabelFieldArray/LabelFieldArray.js, src/components/views/SerialView/SerialView.test.js, src/routes/SerialCreateRoute/SerialCreateRoute.js
- Removed leftover screen debug fromissue publication field test files
- Tweaked keys within mapped arrays to use indexs
- Fixed issue publication field key to use reassigned indexKey
- Tweaked serial view onCLose prop within serials view to be a function instead of string
- Removed redundent form block from serial create route
=> test: Error fixes

src/components/RulesetFormSections/IssuePublicationField/IssuePublicationField.js, src/components/RulesetFormSections/IssuePublicationField/IssuePublicationField.test.js
[UISER-27](https://folio-org.atlassian.net/jira/software/c/projects/ERM/boards/141?selectedIssue=UISER-27)
=> UISER-27, added aria labels

CHANGELOG.md
Added section to changelog relating to 1.0.2 release
=> docs: Updated Changelog from 1.0.2

package.json
Adds serials-management.locales.collection.get permission to module.serials-management.enabled permission set fixing UISER-131
=> UISER-131 Add get locales permission

CHANGELOG.md
Added sections to changelog reflected in 1.0.3 released
=> docs: Updated changelog after 1.0.3 release

package.json
Reverts folio-org/ui-serials-management#266
=> Revert "UISER-133: Incorrect predictedPieces permission case"

src/components/views/SerialView/SerialView.js
Adjusted serial view predicted pieces perm to use correct casing as shown in package
=> fix: Serial view perm tweak

CHANGELOG.md
Added section to changelog reflecting 1.0.4 release
=> docs: Updated changelog post 1.0.4 release

package.json
=> UISER-135 Holdings storage API version update

.eslintrc, src/components/RulesetFormSections/ChronologyField/ChronologyField.js, src/components/RulesetFormSections/ChronologyField/ChronologyField.test.js, src/components/RulesetFormSections/EnumerationNumericFieldArray/EnumerationNumericFieldArray.js, src/components/RulesetFormSections/LabelFieldArray/LabelFieldArray.js, translations/ui-serials-management/en.json
Reverts folio-org/ui-serials-management#278
=> Revert "Uiser 107"

src/components/SerialSections/SerialPOLine/SerialPOLine.js, translations/ui-serials-management/en.json
* add publisher column in PO line card
* add translation key
=> UISER-114 Display publisher information in the serial view

src/components/PiecesPreviewModal/PiecesPreviewModalForm.js
Fixed minor issue in which change function was not handling previous predicted piece selection
=> fix: Starting values onChange

CHANGELOG.md
Added sections to changelog reflected in 1.0.5 released
=> docs: Updated changelog after 1.0.5 release

src/routes/RulesetViewRoute/RulesetViewRoute.js, src/routes/RulesetViewRoute/RulesetViewRoute.test.js
Added initial implementation of rulesetviewroute tests
=> test: RulesetViewRoute test

src/components/PiecesPreviewModal/PiecesPreviewModal.js, src/components/PiecesPreviewModal/PiecesPreviewModal.test.js, src/components/PiecesPreviewModal/PiecesPreviewModalForm.js
Fixed issue in which overlapping date conditional was checking to see if any piece dates were the same as the start date input, where we should instead be checking the match the start date
=> UISER-148: Overlapping date conditional

src/components/GenerateReceivingModal/GenerateReceivingModal.js
Fixed minor issue in which the display sumary was being incorrectly set
UISER-172
=> UISER-172: Receiving pieces for combined pieces do not include correct display summary

package.json
=> UISER-178: Correct predicted piece set deletion permission

CHANGELOG.md
Added changelog section reflected in release 1.1.1
=> chore: Post-release 1.1.1

CHANGELOG.md
Added CHANGELOG.md section reflected in 1.1.2 release
=> chore: Post release 1.1.2

src/routes/RulesetReplaceRoute/RulesetReplaceRoute.js
Fixed an inssue in which the props were being bassed down incorrectly to the ruleset form wtihin the RulesetReplaceRoute
UISER-182
=> UISER-182: Fixed selected model ruleset prop

src/components/GenerateReceivingModal/GenerateReceivingModal/GenerateReceivingModal.js, src/components/RulesetFormSections/ChronologyFieldArray/ChronologyFieldArray.js, src/components/RulesetFormSections/EnumerationFieldArray/EnumerationFieldArray.js, src/components/RulesetFormSections/ModelRulesetSelection/ModelRulesetSelection.js, src/components/RulesetFormSections/PatternTimePeriodForm/PatternTimePeriodForm.js, src/components/RulesetSections/IssuePublication/IssuePublication.js, src/components/views/RulesetView/RulesetView.js
Cleaned up numerous code smells flagged by sonar clodu
=> chore: SonarCloud code smells

src/components/RulesetSections/IssuePublication/IssuePublication.js, src/components/RulesetSections/IssuePublication/IssuePublication.test.js
Added test for the issue publication component
=> test: Issue publication test

src/components/RulesetSections/CombinationRules/CombinationRules.js, src/components/RulesetSections/CombinationRules/CombinationRules.test.js, src/components/RulesetSections/DisplaySummaryTemplate/DisplaySummaryTemplate.test.js, src/components/RulesetSections/OmissionRules/OmissionRules.js, src/components/RulesetSections/OmissionRules/OmissionRules.test.js, src/components/RulesetSections/RulesetInfo/RulesetInfo.js, src/components/RulesetSections/RulesetInfo/RulesetInfo.test.js, test/resources/rulesets/ruleset.js
Added tests for all sections used within the ruleset view component
=> test: Ruleset view sections

CHANGELOG.md, package.json
Bumped dependencies and updated CHANGELOG.md section to reflect release changes
UISER-175
=> chore: Release 2.0.0

CHANGELOG.md, package.json
Bumped version to 2.1.0 and added new CHANGELOG.md section
=> chore: Post release 2.0.0

src/components/RulesetFormSections/ChronologyFieldArray/ChronologyField/ChronologyField.js, src/components/RulesetFormSections/PatternTimePeriodForm/PatternTimePeriodForm.js, src/components/utils/sortPieces.js, src/components/views/RulesetForm/RulesetForm.js
Fixed various code smells and reliability issues
=> chore: Sonar qube code smells/reliability

CHANGELOG.md
Added CHANGELOG.md section from 2.0.1 release
=> chore: Post release 2.0.1

src/components/PiecePublicationDate/PiecePublicationDate.js, src/components/PiecePublicationDate/PiecePublicationDate.test.js, src/components/PieceSetSections/PieceSetInfo/PieceSetInfo.js, src/components/SerialSections/PublicationPattern/PublicationPattern.js, src/components/SerialSections/SerialPieceSets/SerialPieceSets.js, src/routes/PieceSetsRoute/PieceSetsRoute.js
As the systems time zone causes issue with regards to displayed date, should enforce the UTC time zone on all FormattedDate instances
MOODSER-108
=> MODSER-108: Predicted publication date is one day out

src/routes/RulesetCreateRoute/RulesetCreateRoute.js
=> UISER-210: After creating a publication pattern, the publication pattern view should be displayed

src/routes/RulesetCreateRoute/RulesetCreateRoute.js
Fixed an issue in which ruleset owner id was not being correctly assigned
=> fix: Ruleset owner Id

CHANGELOG.md
Added CHANGELOG.md section reflected in 2.0.3 release
=> docs: Post release 2.0.3

src/components/PiecesPreviewModal/PiecesPreviewModalForm/PiecesPreviewModalForm.js
Added timeZone prop to datepicker component to ensure that it lines up with react intl timezoen changes
=> fix: DatePicker timezone
