folio-org/ui-serials-management

package.json

Bumped stripes-kint-components depenedency to 3.0.4, fixes breaking issue with useIntlKeyStore

chore: Stripes-kint-components bump

---

src/components/SerialFormSections/SerialInfoForm/SerialInfoForm.js
src/routes/SerialCreateRoute/SerialCreateRoute.js
src/routes/SerialEditRoute/SerialEditRoute.js
src/routes/SerialsRoute/SerialsRoute.js

Fixed ability for user to unset a serial status
Added temporary lookup columns to SASQLookup for serials
Refactored serial status field name to be based upon .value as opposed to .id for ease of use when handling initial values
Serial status now has initial value of 'active'
[UISER-1](https://issues.folio.org/browse/UISER-1)

fix: Serial info form tidy-up

---

src/components/SerialFormSections/POLineForm/POLineForm.js

Fixed fund link to use correctly named property "fund.fundId" as opposed to the incorrect "fund.id"

fix: Fund link

---

src/hooks/useAcqUnits.js
src/hooks/useIdentifierTypes.js

- Fixed enabled flag to be correctly true/false based on type ids length as opposed to just existing, causing invalid fetches
- Added unique hook query keys to identifierType and acqUnit hooks to ensure fetch is refired each time the parameters passed are changed
- identiferTypeId array passed to identifier-type query is now unique, removing redundant duplicate ids within query string

fix: IdentifierType/AcqUnit hook

---

src/components/RulesetFormSections/CombinationFieldArray/CombinationFieldArray.js
src/components/RulesetFormSections/OmissionFieldArray/OmissionFieldArray.js

Added conditionals to combinations/omissions field array to ensure that only one or the other can be added to ruleset at any time

feat: Omission/Combination disabled

---

src/components/RulesetFormSections/OmissionField/OmissionField.js

Updated max value for week field within IssueWeekMonth omission pattern to represent the weeks within a month as opposed to weeks within a year

fix: IssueWeekMonth omission field

---

src/components/RulesetFormSections/CombinationField/CombinationField.js
src/components/RulesetFormSections/IssuePublicationFieldArray/IssuePublicationFieldArray.js
src/components/RulesetFormSections/OmissionField/OmissionField.js

When a daily issue cycle is selected, deinfed by timeUnit=day and period=1, then the "Days of publication, per cycle" section will not be rendered
[UISER-26](https://issues.folio.org/browse/UISER-26)

feat: Hide "Days of publication, per cycle" section on a daily issue 

---

src/components/RulesetFormSections/PatternTimePeriodForm/PatternTimePeriodForm.js
src/components/views/RulesetForm/RulesetForm.js

Added upper limits to number of time units and issues per time period based on the selected time unit
[UISER-21](https://issues.folio.org/browse/UISER-21), [UISER-24](https://issues.folio.org/browse/UISER-24)

fix: Period and issues validation limits

---

src/components/RulesetFormSections/PatternTimePeriodForm/PatternTimePeriodForm.js

Added optional chaining to time unit limiters issues and period field to prevent crashing on empty form

fix: Time unit limiters safety check

---

src/components/PieceSetSections/PieceSetInfo/PieceSetInfo.js
src/components/PieceSetSections/PiecesList/PiecesList.js
src/components/PiecesPreviewModal/PiecesPreviewModal.js
src/components/SerialSections/ActivePublicationPattern/ActivePublicationPattern.js
src/components/SerialSections/DeprecatedPublicationPatterns/DeprecatedPublicationPatterns.js
src/components/SerialSections/SerialPieceSets/SerialPieceSets.js
src/components/SerialSections/SerialPieceSets/index.js
src/components/SerialSections/index.js
src/components/views/PieceSetView/PieceSetView.js
src/components/views/SerialView/SerialView.js
src/routes/PieceSetsRoute/PieceSetsRoute.js
translations/ui-serials-management/en.json
translations/ui-serials-management/en_US.json

- Added note field to predicted piece set generation modal
- Updated label fields within piece sets preview and view to be display summary
- Added predicted piece sets that are associated with a serial to the serial view pane
- Added link to predicted piece set from serials piece sets MCL, also updated multiple last updated or date generated fields to use FormattedDateTime, instead of FormattedDate
- Added serials associated title to the piece sets pane header
- Fixed conditional for hiding piece sets within serial view
[UISER-50](https://folio-org.atlassian.net/browse/UISER-50), [UISER-46](https://folio-org.atlassian.net/browse/UISER-46), [UISER-56](https://folio-org.atlassian.net/browse/UISER-56)

feat: UI Changes

---

package.json

Fixed typo within picklist.manage display name

chore: Picklist manage permission display name

---

src/components/RulesetFormSections/EnumerationTextualFieldArray/EnumerationTextualFieldArray.js
translations/ui-serials-management/en.json
translations/ui-serials-management/en_US.json

Changed labels within enumeration textual field array, "refdata category" is now "picklist" and "add level" is now "add value"
[UISER-96](https://folio-org.atlassian.net/browse/UISER-96), [UISER-97](https://folio-org.atlassian.net/browse/UISER-97)

fix: Enumeration textual translations

---

src/components/PiecesPreviewModal/PiecesPreviewModal.js
src/components/views/SerialView/SerialView.js

Generate modal button is now primary when the only button within the footer, additionally ensured that pieces cannot be generated if no active ruleset is present
[UISER-72](https://folio-org.atlassian.net/browse/UISER-72)

fix: Preview pieces modal

---

src/components/RulesetFormSections/EnumerationNumericField/EnumerationNumericField.js

Number of units field within enumeration numeric field is now validated as required and a whole number, additionally added aria labels to all associated fields
[UISER-67](https://folio-org.atlassian.net/browse/UISER-67), [UISER-103](https://folio-org.atlassian.net/browse/UISER-103)

fix: Enumeration numeric field tweaks

---

src/components/views/SerialView/SerialView.js
translations/ui-serials-management/en.json

Added serial app logo, serial title and poline number to serial view pane header and sub header along with fallbacks for if a poline has not been attached to the serial
[UISER-65](https://folio-org.atlassian.net/browse/UISER-65)

fix: Serial view missing elements

---

src/components/SerialPOLineInfo/SerialPOLineInfo.js

Added `<ul>` parent elements to mapped lists within serial po line info, additionally fixed an issue in which an empty key value property was not displaying as expected
[UISER-63](https://folio-org.atlassian.net/browse/UISER-63)

fix: Serial PO line info tweaks

---

src/routes/PieceSetsRoute/PieceSetsRoute.js

Fixed accessibility issue “Certain ARIA roles must contain particular children” within serials search and sort
[UISER-74](https://folio-org.atlassian.net/browse/UISER-74)

fix: Accesibility piece set search and sort

---

src/components/RulesetFormSections/CombinationFieldArray/CombinationFieldArray.js
src/components/RulesetFormSections/OmissionFieldArray/OmissionFieldArray.js
src/components/views/RulesetForm/RulesetForm.js

Fixed an accessibility issue “Interactive controls must not be nested” with the omissions and combinations accordions
uiser-66

fix: Accessibility omissions/combinations accordions

---

package.json

Bump version of formatjs/cli to ensure we're bringing in the same version across our modules

build: @formatjs/cli

---

package.json

Ensures that all users of the serials module can read refdata (for dropdown lists etc.)

UISER-95: Add refdata read permission

---

src/components/PiecesPreviewModal/PiecesPreviewModal.js

Fixed an issue in which previewing a ruleset with multiple enumerations resulted in starting value fields being duplciated
[UISER-126](https://folio-org.atlassian.net/browse/UISER-126)

UISER-126: Label starting value fields in preview form are repeated on preview

---

src/components/PiecePublicationDate/PiecePublicationDate.test.js
src/components/SerialFormSections/POLineForm/POLineForm.js
src/routes/SerialEditRoute/SerialEditRoute.js

`POLineForm` useEffect was glueing an object into form state which did not match the shape set up in `initialValues`, causing the form state to always be "dirty" on first mount

UISER-13 UX updates: New/Edit Serial

---

src/components/RulesetFormSections/LabelFieldArray/LabelFieldArray.js

Add default to English, Persist the value even as the user changes the Chronology format, removed from enumeration formats

fix: Minor chronology locale tweaks

---

package.json

Backend permissions were renamed by MODSER-35, but this did not update permissions referenced in UI. This PR corrects this

UISER-133: Bring UI permissions in line with backend permission naming

---

src/components/views/SerialView/SerialView.js

Replacing use of backend permissions (one of which no longer exists with the same name) have been used to conditionally render UI elements. UI permissions used in stead

UISER-133: Use correct UI permissions for displaying UI elements

---

package.json
src/components/views/SerialView/SerialView.js

Tweaked use of hasPerm for ui-serials-management.predictedPieces permission, as all perms are changed to lower case

UISER-133: Incorrect predictedPieces permission case

---

CHANGELOG.md
package.json
src/components/views/SerialView/SerialView.js

Added sections to changelog reflected in 1.0.3 released
Backend permissions were renamed by MODSER-35, but this did not update permissions referenced in UI. This PR corrects this

Release 1.0.4

---

.github/workflows/build-npm.yml
.github/workflows/stuck-license-cla.yml

Added stuck license cla button comment workflow, Prevent buildNPM Snapshot having to run twice on PRs

chore: Workflow tweaks

---

src/components/PiecesPreviewModal/PiecesPreviewModal.js
src/components/PiecesPreviewModal/PiecesPreviewModalForm.js
src/components/views/SerialView/SerialView.js

Removed requirement for a use effect handling the storage of form values within a seperate state
Moved message banner inside the PiecesPreviewForm components so that it can utilise the useFormState values as opposed to new fieldValues duplicate state
Changed showConfirmationModal state to handle both the show/hide boolean values and values being passed to it, this could possibly be refactored to be a useReducer, look into this

refactor: Code review refactors

---

CHANGELOG.md
package.json
src/components/GenerateReceivingModal/GenerateReceivingModal.js
translations/ui-serials-management/en.json

* feat: Add "Create item" checkbox to "Generate in receiving" dialog
Added "Create item" checkbox to recieving pieces modal, as this was not in seperate commits, this part has been cherry picked from the original [UISER-129 PR](https://github.com/folio-org/ui-serials-management/commit/3554ba4f47c9aec7504d2f01907f4ff287648022) 
* chore: Release 1.0.5
Updated app version to 1.0.5 and added section to changelog
UISER-156

Release 1.0.5

---

.github/workflows/build-npm-release.yml
.github/workflows/build-npm.yml

Bumped actions/upload-artifact to v4 due to failing tests when running against deprecated v2

fix: Upload artifact version bump

---

src/routes/SerialsRoute/SerialsRoute.js

In the Serials search and sort view, the “New” button to create a new serial record should only display if the user has permissions to create a new serial, i.e. ui-serials-management.serials.edit

UISER-164: New serial button permission conditional

---

src/components/PiecesPreviewModal/PiecesPreviewModal.js
src/components/utils/index.js
src/components/utils/sortPieces.js
src/components/views/PieceSetView/PieceSetView.js

Added conditional when passing genrated pieces to pieces list, older versions of the  backend fetched an array of pieces, whereas the new endpoint returns a predicted piece set, this conditional sorts if the enpoint is either an object or an array
Merge after mod-serials-management [PR #117](https://github.com/folio-org/mod-serials-management/pull/117)

MODSER-57: Generate pieces deprecation handling

---

src/components/PiecesPreviewModal/PiecesPreviewModalForm.js

- Changed startDate field and select options date to be the piecesets startdate plus a year as opposed to the nextPiece date
- Changed the property nextPieceTemplateMetadata to continuationPieceRecurrenceMetadata in line with backend changes

MODSER-58: Start date changes

---

src/components/PiecesPreviewModal/PiecesPreviewModal.test.js
src/components/PiecesPreviewModal/PiecesPreviewModalForm.js

Updated enumeration field name to use rawValue as opposed to value for correct calculation of future enumeration values, as rawValue is the numeric value and value is the parsed value

MODSER-62: Updated enumeration levels field name

---

package.json

Bumped stripes-erm-testing to version 3.0.0, whilst not released currently there are some helpers which will be used in other PRs, plus seperating this out into its own commit will potentially help us down th line

build: stripes-erm-testing version bump

---

src/components/RulesetFormSections/ChronologyFieldArray/ChronologyFieldArray.js

When using publication templates with chronologies with a locale specified, the locale in the template is not used when applying the template to create a new publication pattern
UISER-196

UISER-196: ModelRuleset locale values

---

src/routes/PieceSetsRoute/PieceSetsRoute.js
src/routes/SerialsRoute/SerialsRoute.js

There was an issue in which selecting a resource within the search and sort would result in the query/filter fields being cleared, we now additionally pass the location.search when navigating to a new view

fix: Persist search and filter queries

---

package.json

Users with permission to create and edit publication patterns should also have the permission to retrieve modelrulesets (publication pattern templates), additionally, although there is no UI, we should support a permission to create and delete modelrulesets
UISER-201, UISER-202

UISER-201/202: Add permission to GET modelRulesets to ui-serials-management.rulesets.edit & Add permission set for managing modelrulesets

---

src/components/RulesetFormSections/EnumerationFieldArray/EnumerationTextualFieldArray/EnumerationTextualFieldArray.js
src/components/RulesetSections/EnumerationLabels/EnumerationLabels.js
src/components/utils/getRulesetFormValues.js

As we use a util function which deep deletes the id key from a ruleset when converting from persistent data to form values, the textual level data was incorrect, additionally ound an issue in which mapping the refdataCategory by desc meant that a new refdataCategory was being created, so mved over to using ID
UISER-204

UISER-204: Textual enumeration labels are not populated in edit/copy screens

---

src/components/PiecesPreviewModal/PiecesPreviewModal.js
src/components/PiecesPreviewModal/PiecesPreviewModalForm/PiecesPreviewModalForm.js
src/components/PiecesPreviewModal/PiecesPreviewModalForm/PiecesPreviewModalForm.test.js

Following on from the previous UISER-211 commit,  we missed a few places in which we use the react-intl format date api and have forgotten to include the timezeon
UISER-211

fix: formateDate timezone inclusion
